// Writes the gitignored env files that point every app at the local stack:
//
//   backend/supabase/functions/.env   secrets for `pnpm functions:serve`
//   extension/.env.localdb            `pnpm dev` / `pnpm build:local` in extension/
//   web/.env.localdb                  `pnpm dev` in web/
//
// Safe to re-run: ENCRYPTION_KEY, ANTHROPIC_API_KEY and STRIPE_WEBHOOK_SECRET
// keep any value already in the file. Run after `pnpm start`.

import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { BACKEND, REPO, localStatus, publishableKey, serviceKey } from './lib.mjs'

const status = localStatus()
const API_URL = status.API_URL

function readEnv(path) {
  if (!existsSync(path)) return {}
  const out = {}
  for (const line of readFileSync(path, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/)
    if (m) out[m[1]] = m[2]
  }
  return out
}

function write(path, lines) {
  writeFileSync(path, lines.join('\n') + '\n')
  console.log(`wrote ${path.slice(REPO.length + 1)}`)
}

// ── Edge Functions ───────────────────────────────────────────────────────────

const fnPath = join(BACKEND, 'supabase', 'functions', '.env')
const fnOld = readEnv(fnPath)
const anthropicKey = fnOld.ANTHROPIC_API_KEY || process.env.ANTHROPIC_API_KEY || ''
write(fnPath, [
  '# Local Edge Function secrets. Generated by `pnpm env:local`; gitignored.',
  '# SUPABASE_URL is injected by `supabase functions serve`.',
  `SERVICE_KEY=${serviceKey(status)}`,
  `ENCRYPTION_KEY=${fnOld.ENCRYPTION_KEY || randomBytes(32).toString('hex')}`,
  '# Real key: generate/tailor call the Anthropic API and cost money.',
  `ANTHROPIC_API_KEY=${anthropicKey}`,
  '# Logs resume text and prompts to the function logs. Local only.',
  `DEBUG_MODE=${fnOld.DEBUG_MODE || 'false'}`,
])
if (!anthropicKey) console.warn('  ANTHROPIC_API_KEY is empty: add one to use generate/tailor from the extension.')

// ── Extension ────────────────────────────────────────────────────────────────

write(join(REPO, 'extension', '.env.localdb'), [
  '# Points the extension at the local Supabase stack. Generated by `pnpm env:local` in backend/.',
  `VITE_SUPABASE_URL=${API_URL}`,
  `VITE_SUPABASE_PUBLISHABLE_KEY=${publishableKey(status)}`,
  'VITE_WEB_URL=http://localhost:3000',
])

// ── Web ──────────────────────────────────────────────────────────────────────

const webPath = join(REPO, 'web', '.env.localdb')
const webOld = readEnv(webPath)
write(webPath, [
  '# Points the web app at the local Supabase stack. Generated by `pnpm env:local` in backend/.',
  '# Stripe keys still come from .env.local (use test-mode keys).',
  `NEXT_PUBLIC_SUPABASE_URL=${API_URL}`,
  `NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${publishableKey(status)}`,
  `SUPABASE_SERVICE_KEY=${serviceKey(status)}`,
  'NEXT_PUBLIC_SITE_URL=http://localhost:3000',
  '# From `stripe listen --print-secret` with your test key pinned (README → local development) (whsec_...).',
  // Left commented until set: an empty value would override .env.local's.
  webOld.STRIPE_WEBHOOK_SECRET ? `STRIPE_WEBHOOK_SECRET=${webOld.STRIPE_WEBHOOK_SECRET}` : '# STRIPE_WEBHOOK_SECRET=',
])
